// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/welcome","name":"首页","icon":"smile","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"营销管理","icon":"table","path":"/list","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"用户管理","icon":"table","path":"/list1","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"商品管理","icon":"table","path":"/list2","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"订单管理","icon":"table","path":"/list3","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"数据分析","icon":"table","path":"/list4","parentId":"ant-design-pro-layout","id":"8"},"9":{"name":"财务管理","icon":"table","path":"/list5","parentId":"ant-design-pro-layout","id":"9"},"10":{"name":"客服管理","icon":"table","path":"/list6","parentId":"ant-design-pro-layout","id":"10"},"11":{"name":"系统设置","icon":"table","path":"/list7","parentId":"ant-design-pro-layout","id":"11"},"12":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"12"},"13":{"path":"*","layout":false,"id":"13"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'12': React.lazy(() => import('./EmptyRoute')),
'13': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/zhangqiang/Documents/GitHub/antd-pro-v6-project/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'/Users/zhangqiang/Documents/GitHub/antd-pro-v6-project/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
