// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/zhangqiang/Documents/GitHub/antd-pro-v6-project/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/Users/zhangqiang/Documents/GitHub/antd-pro-v6-project/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/Users/zhangqiang/Documents/GitHub/antd-pro-v6-project/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
